
export const MOCK_DATA = [
    {
        id: 1,
        nombre: 'Producto 1',
        descripcion: 'algo',
        precio: 1500,
        img: "https://dummyimage.com/200x200/000"
    },
    {
        id: 2,
        nombre: 'Producto 2',
        descripcion: 'algo',
        precio: 1500,
        img: "https://dummyimage.com/200x200/000"
    },
    {
        id: 3,
        nombre: 'Producto 3',
        descripcion: 'algo',
        precio: 1500,
        img: "https://dummyimage.com/200x200/000"
    },
    {
        id: 4,
        nombre: 'Producto 4',
        descripcion: 'algo',
        precio: 1500,
        img: "https://dummyimage.com/200x200/000"
    },
    {
        id: 5,
        nombre: 'Producto 5',
        descripcion: 'algo',
        precio: 1500,
        img: "https://dummyimage.com/200x200/000"
    },

]
